/********************************************************************************
** Form generated from reading UI file 'interfazconfiguracion.ui'
**
** Created by: Qt User Interface Compiler version 5.12.2
**
** WARNING! All changes made in this file will be lost when recompiling UI file!
********************************************************************************/

#ifndef UI_INTERFAZCONFIGURACION_H
#define UI_INTERFAZCONFIGURACION_H

#include <QtCore/QVariant>
#include <QtGui/QIcon>
#include <QtWidgets/QApplication>
#include <QtWidgets/QDialog>
#include <QtWidgets/QDoubleSpinBox>
#include <QtWidgets/QLabel>
#include <QtWidgets/QPushButton>
#include <QtWidgets/QSpinBox>

QT_BEGIN_NAMESPACE

class Ui_InterfazConfiguracion
{
public:
    QPushButton *bConfigurarGranjero;
    QPushButton *bConfigurarOveja;
    QPushButton *bConfigurarCuervo;
    QPushButton *bConfigurarPlaga;
    QPushButton *bConfigurarABB;
    QPushButton *bConfigurarHeap;
    QPushButton *bConfigurarAVL;
    QPushButton *bConfigurarBonus;
    QPushButton *bConfigurarMercado;
    QPushButton *bConfigurarEspanta;
    QLabel *label;
    QSpinBox *delayMovimientoGranjero;
    QLabel *label_2;
    QSpinBox *probabilidadAparicionOveja;
    QLabel *label_3;
    QSpinBox *cantidadOvejasAparecen;
    QSpinBox *cantidadTardanAparecerOvejas;
    QLabel *label_4;
    QSpinBox *segundosOvejaComeFrutos;
    QSpinBox *frutosComeOveja;
    QLabel *label_5;
    QLabel *label_6;
    QLabel *label_7;
    QLabel *label_8;
    QSpinBox *frutosComeCuervo;
    QLabel *label_9;
    QSpinBox *cantidadTardanAparecerCuervos;
    QSpinBox *segundosCuervoComeFrutos;
    QSpinBox *probabilidadAparicionCuervo;
    QSpinBox *cantidadCuervosAparecen;
    QLabel *label_10;
    QLabel *label_12;
    QLabel *label_11;
    QSpinBox *cantidadTardaAparecerPlaga;
    QLabel *label_13;
    QSpinBox *probabilidadAparicionPlaga;
    QLabel *label_14;
    QSpinBox *cantidadSegundosDestruyePlaga;
    QLabel *label_15;
    QLabel *label_16;
    QSpinBox *tiempoAbreMercado;
    QSpinBox *tiempoCierraMercado;
    QDoubleSpinBox *costoEspanta;
    QLabel *label_17;
    QSpinBox *cantidadMaxEspanta;
    QDoubleSpinBox *costoABB;
    QSpinBox *crecimientoABB;
    QLabel *label_20;
    QLabel *label_21;
    QSpinBox *cantSegCosechaABB;
    QSpinBox *frutosCosechaABB;
    QDoubleSpinBox *mayorVentaFrutosABB;
    QLabel *label_22;
    QDoubleSpinBox *menorVentaFrutosABB;
    QLabel *label_23;
    QDoubleSpinBox *costoHeap;
    QSpinBox *cantSegCosechaHeap;
    QLabel *label_25;
    QSpinBox *frutosCosechaHeap;
    QLabel *label_26;
    QDoubleSpinBox *menorVentaFrutosHeap;
    QDoubleSpinBox *mayorVentaFrutosHeap;
    QSpinBox *crecimientoHeap;
    QLabel *label_27;
    QDoubleSpinBox *costoAVL;
    QSpinBox *cantSegCosechaAVL;
    QLabel *label_29;
    QSpinBox *frutosCosechaAVL;
    QLabel *label_30;
    QDoubleSpinBox *menorVentaFrutosAVL;
    QDoubleSpinBox *mayorVentaFrutosAVL;
    QSpinBox *crecimientoAVL;
    QLabel *label_31;
    QDoubleSpinBox *costoBonus;
    QSpinBox *cantSegCosechaBonus;
    QLabel *label_33;
    QSpinBox *frutosCosechaBonus;
    QLabel *label_34;
    QDoubleSpinBox *menorVentaFrutosBonus;
    QDoubleSpinBox *mayorVentaFrutosBonus;
    QSpinBox *crecimientoBonus;
    QLabel *label_35;

    void setupUi(QDialog *InterfazConfiguracion)
    {
        if (InterfazConfiguracion->objectName().isEmpty())
            InterfazConfiguracion->setObjectName(QString::fromUtf8("InterfazConfiguracion"));
        InterfazConfiguracion->resize(827, 556);
        bConfigurarGranjero = new QPushButton(InterfazConfiguracion);
        bConfigurarGranjero->setObjectName(QString::fromUtf8("bConfigurarGranjero"));
        bConfigurarGranjero->setGeometry(QRect(20, 10, 80, 80));
        bConfigurarGranjero->setStyleSheet(QString::fromUtf8("QPushButton:hover{ background-color: rgba(0, 85, 255, 100); }\n"
"QPushButton:pressed{ background-color: rgba(0, 255, 0, 100); }\n"
"QPushButton{ border: 1px solid black; background-color: rgba(255, 255, 255, 10) }\n"
""));
        QIcon icon;
        icon.addFile(QString::fromUtf8(":/farmer/front/Images/Farmer/front/front2.png"), QSize(), QIcon::Normal, QIcon::Off);
        bConfigurarGranjero->setIcon(icon);
        bConfigurarGranjero->setIconSize(QSize(80, 80));
        bConfigurarGranjero->setAutoDefault(false);
        bConfigurarOveja = new QPushButton(InterfazConfiguracion);
        bConfigurarOveja->setObjectName(QString::fromUtf8("bConfigurarOveja"));
        bConfigurarOveja->setGeometry(QRect(160, 10, 80, 80));
        bConfigurarOveja->setStyleSheet(QString::fromUtf8("QPushButton:hover{ background-color: rgba(0, 85, 255, 100); }\n"
"QPushButton:pressed{ background-color: rgba(0, 255, 0, 100); }\n"
"QPushButton{ border: 1px solid black; background-color: rgba(255, 255, 255, 10) }\n"
""));
        QIcon icon1;
        icon1.addFile(QString::fromUtf8(":/oveja/Images/OVEJA.png"), QSize(), QIcon::Normal, QIcon::Off);
        bConfigurarOveja->setIcon(icon1);
        bConfigurarOveja->setIconSize(QSize(80, 80));
        bConfigurarOveja->setAutoDefault(false);
        bConfigurarCuervo = new QPushButton(InterfazConfiguracion);
        bConfigurarCuervo->setObjectName(QString::fromUtf8("bConfigurarCuervo"));
        bConfigurarCuervo->setGeometry(QRect(300, 10, 80, 80));
        bConfigurarCuervo->setStyleSheet(QString::fromUtf8("QPushButton:hover{ background-color: rgba(0, 85, 255, 100); }\n"
"QPushButton:pressed{ background-color: rgba(0, 255, 0, 100); }\n"
"QPushButton{ border: 1px solid black; background-color: rgba(255, 255, 255, 10) }\n"
""));
        QIcon icon2;
        icon2.addFile(QString::fromUtf8(":/cuervo/Images/Raven/raven-black0001.png"), QSize(), QIcon::Normal, QIcon::Off);
        bConfigurarCuervo->setIcon(icon2);
        bConfigurarCuervo->setIconSize(QSize(80, 80));
        bConfigurarCuervo->setAutoDefault(false);
        bConfigurarPlaga = new QPushButton(InterfazConfiguracion);
        bConfigurarPlaga->setObjectName(QString::fromUtf8("bConfigurarPlaga"));
        bConfigurarPlaga->setGeometry(QRect(440, 10, 80, 80));
        bConfigurarPlaga->setStyleSheet(QString::fromUtf8("QPushButton:hover{ background-color: rgba(0, 85, 255, 100); }\n"
"QPushButton:pressed{ background-color: rgba(0, 255, 0, 100); }\n"
"QPushButton{ border: 1px solid black; background-color: rgba(255, 255, 255, 10) }\n"
""));
        QIcon icon3;
        icon3.addFile(QString::fromUtf8(":/arbol/avl/Images/deadtrees/parasitoAVL.png"), QSize(), QIcon::Normal, QIcon::Off);
        bConfigurarPlaga->setIcon(icon3);
        bConfigurarPlaga->setIconSize(QSize(80, 80));
        bConfigurarPlaga->setAutoDefault(false);
        bConfigurarABB = new QPushButton(InterfazConfiguracion);
        bConfigurarABB->setObjectName(QString::fromUtf8("bConfigurarABB"));
        bConfigurarABB->setGeometry(QRect(20, 280, 81, 81));
        bConfigurarABB->setStyleSheet(QString::fromUtf8("QPushButton:hover{ background-color: rgba(0, 85, 255, 100); }\n"
"QPushButton:pressed{ background-color: rgba(0, 255, 0, 100); }\n"
"QPushButton{ border: 1px solid black; background-color: rgba(255, 255, 255, 10) }\n"
""));
        QIcon icon4;
        icon4.addFile(QString::fromUtf8(":/arbol/binario_ordenado/Images/ABB/ABB_00.png"), QSize(), QIcon::Normal, QIcon::Off);
        bConfigurarABB->setIcon(icon4);
        bConfigurarABB->setIconSize(QSize(81, 81));
        bConfigurarABB->setAutoDefault(false);
        bConfigurarHeap = new QPushButton(InterfazConfiguracion);
        bConfigurarHeap->setObjectName(QString::fromUtf8("bConfigurarHeap"));
        bConfigurarHeap->setGeometry(QRect(180, 280, 80, 80));
        bConfigurarHeap->setStyleSheet(QString::fromUtf8("QPushButton:hover{ background-color: rgba(0, 85, 255, 100); }\n"
"QPushButton:pressed{ background-color: rgba(0, 255, 0, 100); }\n"
"QPushButton{ border: 1px solid black; background-color: rgba(255, 255, 255, 10) }\n"
""));
        QIcon icon5;
        icon5.addFile(QString::fromUtf8(":/arbol/heap/Images/HEAP/HEAP_01.png"), QSize(), QIcon::Normal, QIcon::Off);
        bConfigurarHeap->setIcon(icon5);
        bConfigurarHeap->setIconSize(QSize(80, 80));
        bConfigurarHeap->setAutoDefault(false);
        bConfigurarAVL = new QPushButton(InterfazConfiguracion);
        bConfigurarAVL->setObjectName(QString::fromUtf8("bConfigurarAVL"));
        bConfigurarAVL->setGeometry(QRect(340, 280, 80, 80));
        bConfigurarAVL->setStyleSheet(QString::fromUtf8("QPushButton:hover{ background-color: rgba(0, 85, 255, 100); }\n"
"QPushButton:pressed{ background-color: rgba(0, 255, 0, 100); }\n"
"QPushButton{ border: 1px solid black; background-color: rgba(255, 255, 255, 10) }\n"
""));
        QIcon icon6;
        icon6.addFile(QString::fromUtf8(":/arbol/avl/Images/AVL/AVL_03.png"), QSize(), QIcon::Normal, QIcon::Off);
        bConfigurarAVL->setIcon(icon6);
        bConfigurarAVL->setIconSize(QSize(80, 80));
        bConfigurarAVL->setAutoDefault(false);
        bConfigurarBonus = new QPushButton(InterfazConfiguracion);
        bConfigurarBonus->setObjectName(QString::fromUtf8("bConfigurarBonus"));
        bConfigurarBonus->setGeometry(QRect(500, 280, 80, 80));
        bConfigurarBonus->setStyleSheet(QString::fromUtf8("QPushButton:hover{ background-color: rgba(0, 85, 255, 100); }\n"
"QPushButton:pressed{ background-color: rgba(0, 255, 0, 100); }\n"
"QPushButton{ border: 1px solid black; background-color: rgba(255, 255, 255, 10) }\n"
""));
        QIcon icon7;
        icon7.addFile(QString::fromUtf8(":/arbol/bonus/Images/BONUS/BonusTree_03.png"), QSize(), QIcon::Normal, QIcon::Off);
        bConfigurarBonus->setIcon(icon7);
        bConfigurarBonus->setIconSize(QSize(80, 80));
        bConfigurarBonus->setAutoDefault(false);
        bConfigurarMercado = new QPushButton(InterfazConfiguracion);
        bConfigurarMercado->setObjectName(QString::fromUtf8("bConfigurarMercado"));
        bConfigurarMercado->setGeometry(QRect(580, 10, 80, 80));
        bConfigurarMercado->setStyleSheet(QString::fromUtf8("QPushButton:hover{ background-color: rgba(0, 85, 255, 100); }\n"
"QPushButton:pressed{ background-color: rgba(0, 255, 0, 100); }\n"
"QPushButton{ border: 1px solid black; background-color: rgba(255, 255, 255, 10) }\n"
""));
        QIcon icon8;
        icon8.addFile(QString::fromUtf8(":/misc/Images/MercadoChiva.png"), QSize(), QIcon::Normal, QIcon::Off);
        bConfigurarMercado->setIcon(icon8);
        bConfigurarMercado->setIconSize(QSize(80, 80));
        bConfigurarMercado->setAutoDefault(false);
        bConfigurarEspanta = new QPushButton(InterfazConfiguracion);
        bConfigurarEspanta->setObjectName(QString::fromUtf8("bConfigurarEspanta"));
        bConfigurarEspanta->setGeometry(QRect(720, 10, 80, 80));
        bConfigurarEspanta->setStyleSheet(QString::fromUtf8("QPushButton:hover{ background-color: rgba(0, 85, 255, 100); }\n"
"QPushButton:pressed{ background-color: rgba(0, 255, 0, 100); }\n"
"QPushButton{ border: 1px solid black; background-color: rgba(255, 255, 255, 10) }\n"
""));
        QIcon icon9;
        icon9.addFile(QString::fromUtf8(":/misc/Images/Scarecrow.png"), QSize(), QIcon::Normal, QIcon::Off);
        bConfigurarEspanta->setIcon(icon9);
        bConfigurarEspanta->setIconSize(QSize(80, 80));
        bConfigurarEspanta->setAutoDefault(false);
        label = new QLabel(InterfazConfiguracion);
        label->setObjectName(QString::fromUtf8("label"));
        label->setGeometry(QRect(30, 100, 61, 61));
        label->setAlignment(Qt::AlignCenter);
        label->setWordWrap(true);
        delayMovimientoGranjero = new QSpinBox(InterfazConfiguracion);
        delayMovimientoGranjero->setObjectName(QString::fromUtf8("delayMovimientoGranjero"));
        delayMovimientoGranjero->setGeometry(QRect(30, 160, 61, 22));
        delayMovimientoGranjero->setWrapping(true);
        delayMovimientoGranjero->setAlignment(Qt::AlignCenter);
        delayMovimientoGranjero->setButtonSymbols(QAbstractSpinBox::NoButtons);
        delayMovimientoGranjero->setMinimum(1);
        delayMovimientoGranjero->setMaximum(1000000);
        label_2 = new QLabel(InterfazConfiguracion);
        label_2->setObjectName(QString::fromUtf8("label_2"));
        label_2->setGeometry(QRect(160, 90, 81, 21));
        label_2->setAlignment(Qt::AlignCenter);
        label_2->setWordWrap(true);
        probabilidadAparicionOveja = new QSpinBox(InterfazConfiguracion);
        probabilidadAparicionOveja->setObjectName(QString::fromUtf8("probabilidadAparicionOveja"));
        probabilidadAparicionOveja->setGeometry(QRect(170, 110, 61, 22));
        probabilidadAparicionOveja->setWrapping(true);
        probabilidadAparicionOveja->setAlignment(Qt::AlignCenter);
        probabilidadAparicionOveja->setButtonSymbols(QAbstractSpinBox::NoButtons);
        probabilidadAparicionOveja->setMinimum(0);
        probabilidadAparicionOveja->setMaximum(1000000);
        label_3 = new QLabel(InterfazConfiguracion);
        label_3->setObjectName(QString::fromUtf8("label_3"));
        label_3->setGeometry(QRect(170, 130, 61, 16));
        label_3->setAlignment(Qt::AlignCenter);
        cantidadOvejasAparecen = new QSpinBox(InterfazConfiguracion);
        cantidadOvejasAparecen->setObjectName(QString::fromUtf8("cantidadOvejasAparecen"));
        cantidadOvejasAparecen->setGeometry(QRect(150, 150, 42, 22));
        cantidadOvejasAparecen->setWrapping(true);
        cantidadOvejasAparecen->setAlignment(Qt::AlignCenter);
        cantidadOvejasAparecen->setButtonSymbols(QAbstractSpinBox::NoButtons);
        cantidadOvejasAparecen->setMinimum(1);
        cantidadOvejasAparecen->setMaximum(1000000);
        cantidadTardanAparecerOvejas = new QSpinBox(InterfazConfiguracion);
        cantidadTardanAparecerOvejas->setObjectName(QString::fromUtf8("cantidadTardanAparecerOvejas"));
        cantidadTardanAparecerOvejas->setGeometry(QRect(210, 150, 42, 22));
        cantidadTardanAparecerOvejas->setWrapping(true);
        cantidadTardanAparecerOvejas->setAlignment(Qt::AlignCenter);
        cantidadTardanAparecerOvejas->setButtonSymbols(QAbstractSpinBox::NoButtons);
        cantidadTardanAparecerOvejas->setMinimum(1);
        cantidadTardanAparecerOvejas->setMaximum(1000000);
        label_4 = new QLabel(InterfazConfiguracion);
        label_4->setObjectName(QString::fromUtf8("label_4"));
        label_4->setGeometry(QRect(170, 170, 61, 16));
        label_4->setAlignment(Qt::AlignCenter);
        segundosOvejaComeFrutos = new QSpinBox(InterfazConfiguracion);
        segundosOvejaComeFrutos->setObjectName(QString::fromUtf8("segundosOvejaComeFrutos"));
        segundosOvejaComeFrutos->setGeometry(QRect(210, 190, 42, 22));
        segundosOvejaComeFrutos->setWrapping(true);
        segundosOvejaComeFrutos->setAlignment(Qt::AlignCenter);
        segundosOvejaComeFrutos->setButtonSymbols(QAbstractSpinBox::NoButtons);
        segundosOvejaComeFrutos->setMinimum(1);
        segundosOvejaComeFrutos->setMaximum(1000000);
        frutosComeOveja = new QSpinBox(InterfazConfiguracion);
        frutosComeOveja->setObjectName(QString::fromUtf8("frutosComeOveja"));
        frutosComeOveja->setGeometry(QRect(150, 190, 42, 22));
        frutosComeOveja->setWrapping(true);
        frutosComeOveja->setAlignment(Qt::AlignCenter);
        frutosComeOveja->setButtonSymbols(QAbstractSpinBox::NoButtons);
        frutosComeOveja->setMinimum(1);
        frutosComeOveja->setMaximum(1000000);
        label_5 = new QLabel(InterfazConfiguracion);
        label_5->setObjectName(QString::fromUtf8("label_5"));
        label_5->setGeometry(QRect(20, 260, 81, 20));
        label_5->setAlignment(Qt::AlignCenter);
        label_6 = new QLabel(InterfazConfiguracion);
        label_6->setObjectName(QString::fromUtf8("label_6"));
        label_6->setGeometry(QRect(180, 260, 81, 20));
        label_6->setAlignment(Qt::AlignCenter);
        label_7 = new QLabel(InterfazConfiguracion);
        label_7->setObjectName(QString::fromUtf8("label_7"));
        label_7->setGeometry(QRect(340, 260, 81, 20));
        label_7->setAlignment(Qt::AlignCenter);
        label_8 = new QLabel(InterfazConfiguracion);
        label_8->setObjectName(QString::fromUtf8("label_8"));
        label_8->setGeometry(QRect(500, 260, 81, 20));
        label_8->setAlignment(Qt::AlignCenter);
        frutosComeCuervo = new QSpinBox(InterfazConfiguracion);
        frutosComeCuervo->setObjectName(QString::fromUtf8("frutosComeCuervo"));
        frutosComeCuervo->setGeometry(QRect(290, 190, 42, 22));
        frutosComeCuervo->setWrapping(true);
        frutosComeCuervo->setAlignment(Qt::AlignCenter);
        frutosComeCuervo->setButtonSymbols(QAbstractSpinBox::NoButtons);
        frutosComeCuervo->setMinimum(1);
        frutosComeCuervo->setMaximum(1000000);
        label_9 = new QLabel(InterfazConfiguracion);
        label_9->setObjectName(QString::fromUtf8("label_9"));
        label_9->setGeometry(QRect(310, 130, 61, 16));
        label_9->setAlignment(Qt::AlignCenter);
        cantidadTardanAparecerCuervos = new QSpinBox(InterfazConfiguracion);
        cantidadTardanAparecerCuervos->setObjectName(QString::fromUtf8("cantidadTardanAparecerCuervos"));
        cantidadTardanAparecerCuervos->setGeometry(QRect(350, 150, 42, 22));
        cantidadTardanAparecerCuervos->setWrapping(true);
        cantidadTardanAparecerCuervos->setAlignment(Qt::AlignCenter);
        cantidadTardanAparecerCuervos->setButtonSymbols(QAbstractSpinBox::NoButtons);
        cantidadTardanAparecerCuervos->setMinimum(1);
        cantidadTardanAparecerCuervos->setMaximum(1000000);
        segundosCuervoComeFrutos = new QSpinBox(InterfazConfiguracion);
        segundosCuervoComeFrutos->setObjectName(QString::fromUtf8("segundosCuervoComeFrutos"));
        segundosCuervoComeFrutos->setGeometry(QRect(350, 190, 42, 22));
        segundosCuervoComeFrutos->setWrapping(true);
        segundosCuervoComeFrutos->setAlignment(Qt::AlignCenter);
        segundosCuervoComeFrutos->setButtonSymbols(QAbstractSpinBox::NoButtons);
        segundosCuervoComeFrutos->setMinimum(1);
        segundosCuervoComeFrutos->setMaximum(1000000);
        probabilidadAparicionCuervo = new QSpinBox(InterfazConfiguracion);
        probabilidadAparicionCuervo->setObjectName(QString::fromUtf8("probabilidadAparicionCuervo"));
        probabilidadAparicionCuervo->setGeometry(QRect(310, 110, 61, 22));
        probabilidadAparicionCuervo->setWrapping(true);
        probabilidadAparicionCuervo->setAlignment(Qt::AlignCenter);
        probabilidadAparicionCuervo->setButtonSymbols(QAbstractSpinBox::NoButtons);
        probabilidadAparicionCuervo->setMinimum(0);
        probabilidadAparicionCuervo->setMaximum(1000000);
        cantidadCuervosAparecen = new QSpinBox(InterfazConfiguracion);
        cantidadCuervosAparecen->setObjectName(QString::fromUtf8("cantidadCuervosAparecen"));
        cantidadCuervosAparecen->setGeometry(QRect(290, 150, 42, 22));
        cantidadCuervosAparecen->setWrapping(true);
        cantidadCuervosAparecen->setAlignment(Qt::AlignCenter);
        cantidadCuervosAparecen->setButtonSymbols(QAbstractSpinBox::NoButtons);
        cantidadCuervosAparecen->setMinimum(1);
        cantidadCuervosAparecen->setMaximum(1000000);
        label_10 = new QLabel(InterfazConfiguracion);
        label_10->setObjectName(QString::fromUtf8("label_10"));
        label_10->setGeometry(QRect(300, 90, 81, 21));
        label_10->setAlignment(Qt::AlignCenter);
        label_10->setWordWrap(true);
        label_12 = new QLabel(InterfazConfiguracion);
        label_12->setObjectName(QString::fromUtf8("label_12"));
        label_12->setGeometry(QRect(310, 170, 61, 16));
        label_12->setAlignment(Qt::AlignCenter);
        label_11 = new QLabel(InterfazConfiguracion);
        label_11->setObjectName(QString::fromUtf8("label_11"));
        label_11->setGeometry(QRect(440, 130, 81, 20));
        label_11->setAlignment(Qt::AlignCenter);
        cantidadTardaAparecerPlaga = new QSpinBox(InterfazConfiguracion);
        cantidadTardaAparecerPlaga->setObjectName(QString::fromUtf8("cantidadTardaAparecerPlaga"));
        cantidadTardaAparecerPlaga->setGeometry(QRect(450, 150, 61, 22));
        cantidadTardaAparecerPlaga->setWrapping(true);
        cantidadTardaAparecerPlaga->setAlignment(Qt::AlignCenter);
        cantidadTardaAparecerPlaga->setButtonSymbols(QAbstractSpinBox::NoButtons);
        cantidadTardaAparecerPlaga->setMinimum(1);
        cantidadTardaAparecerPlaga->setMaximum(1000000);
        label_13 = new QLabel(InterfazConfiguracion);
        label_13->setObjectName(QString::fromUtf8("label_13"));
        label_13->setGeometry(QRect(440, 90, 81, 21));
        label_13->setAlignment(Qt::AlignCenter);
        label_13->setWordWrap(true);
        probabilidadAparicionPlaga = new QSpinBox(InterfazConfiguracion);
        probabilidadAparicionPlaga->setObjectName(QString::fromUtf8("probabilidadAparicionPlaga"));
        probabilidadAparicionPlaga->setGeometry(QRect(450, 110, 61, 22));
        probabilidadAparicionPlaga->setWrapping(true);
        probabilidadAparicionPlaga->setAlignment(Qt::AlignCenter);
        probabilidadAparicionPlaga->setButtonSymbols(QAbstractSpinBox::NoButtons);
        probabilidadAparicionPlaga->setMinimum(0);
        probabilidadAparicionPlaga->setMaximum(1000000);
        label_14 = new QLabel(InterfazConfiguracion);
        label_14->setObjectName(QString::fromUtf8("label_14"));
        label_14->setGeometry(QRect(440, 180, 81, 31));
        label_14->setAlignment(Qt::AlignCenter);
        label_14->setWordWrap(true);
        cantidadSegundosDestruyePlaga = new QSpinBox(InterfazConfiguracion);
        cantidadSegundosDestruyePlaga->setObjectName(QString::fromUtf8("cantidadSegundosDestruyePlaga"));
        cantidadSegundosDestruyePlaga->setGeometry(QRect(450, 210, 61, 22));
        cantidadSegundosDestruyePlaga->setWrapping(true);
        cantidadSegundosDestruyePlaga->setAlignment(Qt::AlignCenter);
        cantidadSegundosDestruyePlaga->setButtonSymbols(QAbstractSpinBox::NoButtons);
        cantidadSegundosDestruyePlaga->setMinimum(1);
        cantidadSegundosDestruyePlaga->setMaximum(1000000);
        label_15 = new QLabel(InterfazConfiguracion);
        label_15->setObjectName(QString::fromUtf8("label_15"));
        label_15->setGeometry(QRect(580, 90, 81, 20));
        label_15->setAlignment(Qt::AlignCenter);
        label_16 = new QLabel(InterfazConfiguracion);
        label_16->setObjectName(QString::fromUtf8("label_16"));
        label_16->setGeometry(QRect(580, 130, 81, 20));
        label_16->setAlignment(Qt::AlignCenter);
        tiempoAbreMercado = new QSpinBox(InterfazConfiguracion);
        tiempoAbreMercado->setObjectName(QString::fromUtf8("tiempoAbreMercado"));
        tiempoAbreMercado->setGeometry(QRect(590, 110, 61, 22));
        tiempoAbreMercado->setWrapping(true);
        tiempoAbreMercado->setAlignment(Qt::AlignCenter);
        tiempoAbreMercado->setButtonSymbols(QAbstractSpinBox::NoButtons);
        tiempoAbreMercado->setMinimum(1);
        tiempoAbreMercado->setMaximum(1000000);
        tiempoCierraMercado = new QSpinBox(InterfazConfiguracion);
        tiempoCierraMercado->setObjectName(QString::fromUtf8("tiempoCierraMercado"));
        tiempoCierraMercado->setGeometry(QRect(590, 150, 61, 22));
        tiempoCierraMercado->setWrapping(true);
        tiempoCierraMercado->setAlignment(Qt::AlignCenter);
        tiempoCierraMercado->setButtonSymbols(QAbstractSpinBox::NoButtons);
        tiempoCierraMercado->setMinimum(1);
        tiempoCierraMercado->setMaximum(1000000);
        costoEspanta = new QDoubleSpinBox(InterfazConfiguracion);
        costoEspanta->setObjectName(QString::fromUtf8("costoEspanta"));
        costoEspanta->setGeometry(QRect(730, 110, 61, 22));
        costoEspanta->setWrapping(true);
        costoEspanta->setAlignment(Qt::AlignCenter);
        costoEspanta->setButtonSymbols(QAbstractSpinBox::NoButtons);
        costoEspanta->setDecimals(2);
        costoEspanta->setMinimum(1.000000000000000);
        costoEspanta->setMaximum(9999999999.000000000000000);
        label_17 = new QLabel(InterfazConfiguracion);
        label_17->setObjectName(QString::fromUtf8("label_17"));
        label_17->setGeometry(QRect(720, 130, 81, 20));
        label_17->setAlignment(Qt::AlignCenter);
        cantidadMaxEspanta = new QSpinBox(InterfazConfiguracion);
        cantidadMaxEspanta->setObjectName(QString::fromUtf8("cantidadMaxEspanta"));
        cantidadMaxEspanta->setGeometry(QRect(730, 150, 61, 22));
        cantidadMaxEspanta->setWrapping(true);
        cantidadMaxEspanta->setAlignment(Qt::AlignCenter);
        cantidadMaxEspanta->setButtonSymbols(QAbstractSpinBox::NoButtons);
        cantidadMaxEspanta->setMinimum(0);
        cantidadMaxEspanta->setMaximum(1000000);
        costoABB = new QDoubleSpinBox(InterfazConfiguracion);
        costoABB->setObjectName(QString::fromUtf8("costoABB"));
        costoABB->setGeometry(QRect(20, 380, 81, 22));
        costoABB->setWrapping(true);
        costoABB->setAlignment(Qt::AlignCenter);
        costoABB->setButtonSymbols(QAbstractSpinBox::NoButtons);
        costoABB->setDecimals(2);
        costoABB->setMinimum(1.000000000000000);
        costoABB->setMaximum(9999999999.000000000000000);
        crecimientoABB = new QSpinBox(InterfazConfiguracion);
        crecimientoABB->setObjectName(QString::fromUtf8("crecimientoABB"));
        crecimientoABB->setGeometry(QRect(20, 430, 81, 22));
        crecimientoABB->setWrapping(true);
        crecimientoABB->setAlignment(Qt::AlignCenter);
        crecimientoABB->setButtonSymbols(QAbstractSpinBox::NoButtons);
        crecimientoABB->setMinimum(1);
        crecimientoABB->setMaximum(1000000);
        label_20 = new QLabel(InterfazConfiguracion);
        label_20->setObjectName(QString::fromUtf8("label_20"));
        label_20->setGeometry(QRect(20, 400, 81, 31));
        label_20->setAlignment(Qt::AlignCenter);
        label_20->setWordWrap(true);
        label_21 = new QLabel(InterfazConfiguracion);
        label_21->setObjectName(QString::fromUtf8("label_21"));
        label_21->setGeometry(QRect(30, 450, 61, 16));
        label_21->setAlignment(Qt::AlignCenter);
        cantSegCosechaABB = new QSpinBox(InterfazConfiguracion);
        cantSegCosechaABB->setObjectName(QString::fromUtf8("cantSegCosechaABB"));
        cantSegCosechaABB->setGeometry(QRect(70, 470, 42, 22));
        cantSegCosechaABB->setWrapping(true);
        cantSegCosechaABB->setAlignment(Qt::AlignCenter);
        cantSegCosechaABB->setButtonSymbols(QAbstractSpinBox::NoButtons);
        cantSegCosechaABB->setMinimum(1);
        cantSegCosechaABB->setMaximum(1000000);
        frutosCosechaABB = new QSpinBox(InterfazConfiguracion);
        frutosCosechaABB->setObjectName(QString::fromUtf8("frutosCosechaABB"));
        frutosCosechaABB->setGeometry(QRect(10, 470, 42, 22));
        frutosCosechaABB->setWrapping(true);
        frutosCosechaABB->setAlignment(Qt::AlignCenter);
        frutosCosechaABB->setButtonSymbols(QAbstractSpinBox::NoButtons);
        frutosCosechaABB->setMinimum(1);
        frutosCosechaABB->setMaximum(1000000);
        mayorVentaFrutosABB = new QDoubleSpinBox(InterfazConfiguracion);
        mayorVentaFrutosABB->setObjectName(QString::fromUtf8("mayorVentaFrutosABB"));
        mayorVentaFrutosABB->setGeometry(QRect(70, 520, 42, 22));
        mayorVentaFrutosABB->setWrapping(true);
        mayorVentaFrutosABB->setAlignment(Qt::AlignCenter);
        mayorVentaFrutosABB->setButtonSymbols(QAbstractSpinBox::NoButtons);
        mayorVentaFrutosABB->setDecimals(2);
        mayorVentaFrutosABB->setMinimum(1.000000000000000);
        mayorVentaFrutosABB->setMaximum(9999999999.000000000000000);
        label_22 = new QLabel(InterfazConfiguracion);
        label_22->setObjectName(QString::fromUtf8("label_22"));
        label_22->setGeometry(QRect(20, 490, 81, 31));
        label_22->setAlignment(Qt::AlignCenter);
        label_22->setWordWrap(true);
        menorVentaFrutosABB = new QDoubleSpinBox(InterfazConfiguracion);
        menorVentaFrutosABB->setObjectName(QString::fromUtf8("menorVentaFrutosABB"));
        menorVentaFrutosABB->setGeometry(QRect(10, 520, 42, 22));
        menorVentaFrutosABB->setWrapping(true);
        menorVentaFrutosABB->setAlignment(Qt::AlignCenter);
        menorVentaFrutosABB->setButtonSymbols(QAbstractSpinBox::NoButtons);
        menorVentaFrutosABB->setDecimals(2);
        menorVentaFrutosABB->setMinimum(1.000000000000000);
        menorVentaFrutosABB->setMaximum(9999999999.000000000000000);
        label_23 = new QLabel(InterfazConfiguracion);
        label_23->setObjectName(QString::fromUtf8("label_23"));
        label_23->setGeometry(QRect(180, 400, 81, 31));
        label_23->setAlignment(Qt::AlignCenter);
        label_23->setWordWrap(true);
        costoHeap = new QDoubleSpinBox(InterfazConfiguracion);
        costoHeap->setObjectName(QString::fromUtf8("costoHeap"));
        costoHeap->setGeometry(QRect(180, 380, 81, 22));
        costoHeap->setWrapping(true);
        costoHeap->setAlignment(Qt::AlignCenter);
        costoHeap->setButtonSymbols(QAbstractSpinBox::NoButtons);
        costoHeap->setDecimals(2);
        costoHeap->setMinimum(1.000000000000000);
        costoHeap->setMaximum(9999999999.000000000000000);
        cantSegCosechaHeap = new QSpinBox(InterfazConfiguracion);
        cantSegCosechaHeap->setObjectName(QString::fromUtf8("cantSegCosechaHeap"));
        cantSegCosechaHeap->setGeometry(QRect(230, 470, 42, 22));
        cantSegCosechaHeap->setWrapping(true);
        cantSegCosechaHeap->setAlignment(Qt::AlignCenter);
        cantSegCosechaHeap->setButtonSymbols(QAbstractSpinBox::NoButtons);
        cantSegCosechaHeap->setMinimum(1);
        cantSegCosechaHeap->setMaximum(1000000);
        label_25 = new QLabel(InterfazConfiguracion);
        label_25->setObjectName(QString::fromUtf8("label_25"));
        label_25->setGeometry(QRect(190, 450, 61, 16));
        label_25->setAlignment(Qt::AlignCenter);
        frutosCosechaHeap = new QSpinBox(InterfazConfiguracion);
        frutosCosechaHeap->setObjectName(QString::fromUtf8("frutosCosechaHeap"));
        frutosCosechaHeap->setGeometry(QRect(170, 470, 42, 22));
        frutosCosechaHeap->setWrapping(true);
        frutosCosechaHeap->setAlignment(Qt::AlignCenter);
        frutosCosechaHeap->setButtonSymbols(QAbstractSpinBox::NoButtons);
        frutosCosechaHeap->setMinimum(1);
        frutosCosechaHeap->setMaximum(1000000);
        label_26 = new QLabel(InterfazConfiguracion);
        label_26->setObjectName(QString::fromUtf8("label_26"));
        label_26->setGeometry(QRect(180, 490, 81, 31));
        label_26->setAlignment(Qt::AlignCenter);
        label_26->setWordWrap(true);
        menorVentaFrutosHeap = new QDoubleSpinBox(InterfazConfiguracion);
        menorVentaFrutosHeap->setObjectName(QString::fromUtf8("menorVentaFrutosHeap"));
        menorVentaFrutosHeap->setGeometry(QRect(170, 520, 42, 22));
        menorVentaFrutosHeap->setWrapping(true);
        menorVentaFrutosHeap->setAlignment(Qt::AlignCenter);
        menorVentaFrutosHeap->setButtonSymbols(QAbstractSpinBox::NoButtons);
        menorVentaFrutosHeap->setDecimals(2);
        menorVentaFrutosHeap->setMinimum(1.000000000000000);
        menorVentaFrutosHeap->setMaximum(9999999999.000000000000000);
        mayorVentaFrutosHeap = new QDoubleSpinBox(InterfazConfiguracion);
        mayorVentaFrutosHeap->setObjectName(QString::fromUtf8("mayorVentaFrutosHeap"));
        mayorVentaFrutosHeap->setGeometry(QRect(230, 520, 42, 22));
        mayorVentaFrutosHeap->setWrapping(true);
        mayorVentaFrutosHeap->setAlignment(Qt::AlignCenter);
        mayorVentaFrutosHeap->setButtonSymbols(QAbstractSpinBox::NoButtons);
        mayorVentaFrutosHeap->setDecimals(2);
        mayorVentaFrutosHeap->setMinimum(1.000000000000000);
        mayorVentaFrutosHeap->setMaximum(9999999999.000000000000000);
        crecimientoHeap = new QSpinBox(InterfazConfiguracion);
        crecimientoHeap->setObjectName(QString::fromUtf8("crecimientoHeap"));
        crecimientoHeap->setGeometry(QRect(180, 430, 81, 22));
        crecimientoHeap->setWrapping(true);
        crecimientoHeap->setAlignment(Qt::AlignCenter);
        crecimientoHeap->setButtonSymbols(QAbstractSpinBox::NoButtons);
        crecimientoHeap->setMinimum(1);
        crecimientoHeap->setMaximum(1000000);
        label_27 = new QLabel(InterfazConfiguracion);
        label_27->setObjectName(QString::fromUtf8("label_27"));
        label_27->setGeometry(QRect(340, 400, 81, 31));
        label_27->setAlignment(Qt::AlignCenter);
        label_27->setWordWrap(true);
        costoAVL = new QDoubleSpinBox(InterfazConfiguracion);
        costoAVL->setObjectName(QString::fromUtf8("costoAVL"));
        costoAVL->setGeometry(QRect(340, 380, 81, 22));
        costoAVL->setWrapping(true);
        costoAVL->setAlignment(Qt::AlignCenter);
        costoAVL->setButtonSymbols(QAbstractSpinBox::NoButtons);
        costoAVL->setDecimals(2);
        costoAVL->setMinimum(1.000000000000000);
        costoAVL->setMaximum(9999999999.000000000000000);
        cantSegCosechaAVL = new QSpinBox(InterfazConfiguracion);
        cantSegCosechaAVL->setObjectName(QString::fromUtf8("cantSegCosechaAVL"));
        cantSegCosechaAVL->setGeometry(QRect(390, 470, 42, 22));
        cantSegCosechaAVL->setWrapping(true);
        cantSegCosechaAVL->setAlignment(Qt::AlignCenter);
        cantSegCosechaAVL->setButtonSymbols(QAbstractSpinBox::NoButtons);
        cantSegCosechaAVL->setMinimum(1);
        cantSegCosechaAVL->setMaximum(1000000);
        label_29 = new QLabel(InterfazConfiguracion);
        label_29->setObjectName(QString::fromUtf8("label_29"));
        label_29->setGeometry(QRect(350, 450, 61, 16));
        label_29->setAlignment(Qt::AlignCenter);
        frutosCosechaAVL = new QSpinBox(InterfazConfiguracion);
        frutosCosechaAVL->setObjectName(QString::fromUtf8("frutosCosechaAVL"));
        frutosCosechaAVL->setGeometry(QRect(330, 470, 42, 22));
        frutosCosechaAVL->setWrapping(true);
        frutosCosechaAVL->setAlignment(Qt::AlignCenter);
        frutosCosechaAVL->setButtonSymbols(QAbstractSpinBox::NoButtons);
        frutosCosechaAVL->setMinimum(1);
        frutosCosechaAVL->setMaximum(1000000);
        label_30 = new QLabel(InterfazConfiguracion);
        label_30->setObjectName(QString::fromUtf8("label_30"));
        label_30->setGeometry(QRect(340, 490, 81, 31));
        label_30->setAlignment(Qt::AlignCenter);
        label_30->setWordWrap(true);
        menorVentaFrutosAVL = new QDoubleSpinBox(InterfazConfiguracion);
        menorVentaFrutosAVL->setObjectName(QString::fromUtf8("menorVentaFrutosAVL"));
        menorVentaFrutosAVL->setGeometry(QRect(330, 520, 42, 22));
        menorVentaFrutosAVL->setWrapping(true);
        menorVentaFrutosAVL->setAlignment(Qt::AlignCenter);
        menorVentaFrutosAVL->setButtonSymbols(QAbstractSpinBox::NoButtons);
        menorVentaFrutosAVL->setDecimals(2);
        menorVentaFrutosAVL->setMinimum(1.000000000000000);
        menorVentaFrutosAVL->setMaximum(9999999999.000000000000000);
        mayorVentaFrutosAVL = new QDoubleSpinBox(InterfazConfiguracion);
        mayorVentaFrutosAVL->setObjectName(QString::fromUtf8("mayorVentaFrutosAVL"));
        mayorVentaFrutosAVL->setGeometry(QRect(390, 520, 42, 22));
        mayorVentaFrutosAVL->setWrapping(true);
        mayorVentaFrutosAVL->setAlignment(Qt::AlignCenter);
        mayorVentaFrutosAVL->setButtonSymbols(QAbstractSpinBox::NoButtons);
        mayorVentaFrutosAVL->setDecimals(2);
        mayorVentaFrutosAVL->setMinimum(1.000000000000000);
        mayorVentaFrutosAVL->setMaximum(9999999999.000000000000000);
        crecimientoAVL = new QSpinBox(InterfazConfiguracion);
        crecimientoAVL->setObjectName(QString::fromUtf8("crecimientoAVL"));
        crecimientoAVL->setGeometry(QRect(340, 430, 81, 22));
        crecimientoAVL->setWrapping(true);
        crecimientoAVL->setAlignment(Qt::AlignCenter);
        crecimientoAVL->setButtonSymbols(QAbstractSpinBox::NoButtons);
        crecimientoAVL->setMinimum(1);
        crecimientoAVL->setMaximum(1000000);
        label_31 = new QLabel(InterfazConfiguracion);
        label_31->setObjectName(QString::fromUtf8("label_31"));
        label_31->setGeometry(QRect(500, 400, 81, 31));
        label_31->setAlignment(Qt::AlignCenter);
        label_31->setWordWrap(true);
        costoBonus = new QDoubleSpinBox(InterfazConfiguracion);
        costoBonus->setObjectName(QString::fromUtf8("costoBonus"));
        costoBonus->setGeometry(QRect(500, 380, 81, 22));
        costoBonus->setWrapping(true);
        costoBonus->setAlignment(Qt::AlignCenter);
        costoBonus->setButtonSymbols(QAbstractSpinBox::NoButtons);
        costoBonus->setDecimals(2);
        costoBonus->setMinimum(1.000000000000000);
        costoBonus->setMaximum(9999999999.000000000000000);
        cantSegCosechaBonus = new QSpinBox(InterfazConfiguracion);
        cantSegCosechaBonus->setObjectName(QString::fromUtf8("cantSegCosechaBonus"));
        cantSegCosechaBonus->setGeometry(QRect(550, 470, 42, 22));
        cantSegCosechaBonus->setWrapping(true);
        cantSegCosechaBonus->setAlignment(Qt::AlignCenter);
        cantSegCosechaBonus->setButtonSymbols(QAbstractSpinBox::NoButtons);
        cantSegCosechaBonus->setMinimum(1);
        cantSegCosechaBonus->setMaximum(1000000);
        label_33 = new QLabel(InterfazConfiguracion);
        label_33->setObjectName(QString::fromUtf8("label_33"));
        label_33->setGeometry(QRect(510, 450, 61, 16));
        label_33->setAlignment(Qt::AlignCenter);
        frutosCosechaBonus = new QSpinBox(InterfazConfiguracion);
        frutosCosechaBonus->setObjectName(QString::fromUtf8("frutosCosechaBonus"));
        frutosCosechaBonus->setGeometry(QRect(490, 470, 42, 22));
        frutosCosechaBonus->setWrapping(true);
        frutosCosechaBonus->setAlignment(Qt::AlignCenter);
        frutosCosechaBonus->setButtonSymbols(QAbstractSpinBox::NoButtons);
        frutosCosechaBonus->setMinimum(1);
        frutosCosechaBonus->setMaximum(1000000);
        label_34 = new QLabel(InterfazConfiguracion);
        label_34->setObjectName(QString::fromUtf8("label_34"));
        label_34->setGeometry(QRect(500, 490, 81, 31));
        label_34->setAlignment(Qt::AlignCenter);
        label_34->setWordWrap(true);
        menorVentaFrutosBonus = new QDoubleSpinBox(InterfazConfiguracion);
        menorVentaFrutosBonus->setObjectName(QString::fromUtf8("menorVentaFrutosBonus"));
        menorVentaFrutosBonus->setGeometry(QRect(490, 520, 42, 22));
        menorVentaFrutosBonus->setWrapping(true);
        menorVentaFrutosBonus->setAlignment(Qt::AlignCenter);
        menorVentaFrutosBonus->setButtonSymbols(QAbstractSpinBox::NoButtons);
        menorVentaFrutosBonus->setDecimals(2);
        menorVentaFrutosBonus->setMinimum(1.000000000000000);
        menorVentaFrutosBonus->setMaximum(9999999999.000000000000000);
        mayorVentaFrutosBonus = new QDoubleSpinBox(InterfazConfiguracion);
        mayorVentaFrutosBonus->setObjectName(QString::fromUtf8("mayorVentaFrutosBonus"));
        mayorVentaFrutosBonus->setGeometry(QRect(550, 520, 42, 22));
        mayorVentaFrutosBonus->setWrapping(true);
        mayorVentaFrutosBonus->setAlignment(Qt::AlignCenter);
        mayorVentaFrutosBonus->setButtonSymbols(QAbstractSpinBox::NoButtons);
        mayorVentaFrutosBonus->setDecimals(2);
        mayorVentaFrutosBonus->setMinimum(1.000000000000000);
        mayorVentaFrutosBonus->setMaximum(9999999999.000000000000000);
        crecimientoBonus = new QSpinBox(InterfazConfiguracion);
        crecimientoBonus->setObjectName(QString::fromUtf8("crecimientoBonus"));
        crecimientoBonus->setGeometry(QRect(500, 430, 81, 22));
        crecimientoBonus->setWrapping(true);
        crecimientoBonus->setAlignment(Qt::AlignCenter);
        crecimientoBonus->setButtonSymbols(QAbstractSpinBox::NoButtons);
        crecimientoBonus->setMinimum(1);
        crecimientoBonus->setMaximum(1000000);
        label_35 = new QLabel(InterfazConfiguracion);
        label_35->setObjectName(QString::fromUtf8("label_35"));
        label_35->setGeometry(QRect(660, 470, 161, 81));
        label_35->setAlignment(Qt::AlignCenter);
        label_35->setWordWrap(true);

        retranslateUi(InterfazConfiguracion);

        bConfigurarGranjero->setDefault(true);
        bConfigurarOveja->setDefault(true);
        bConfigurarCuervo->setDefault(true);
        bConfigurarPlaga->setDefault(true);
        bConfigurarABB->setDefault(true);
        bConfigurarHeap->setDefault(true);
        bConfigurarAVL->setDefault(true);
        bConfigurarBonus->setDefault(true);
        bConfigurarMercado->setDefault(true);
        bConfigurarEspanta->setDefault(true);


        QMetaObject::connectSlotsByName(InterfazConfiguracion);
    } // setupUi

    void retranslateUi(QDialog *InterfazConfiguracion)
    {
        InterfazConfiguracion->setWindowTitle(QApplication::translate("InterfazConfiguracion", "Dialog", nullptr));
        bConfigurarGranjero->setText(QString());
        bConfigurarOveja->setText(QString());
        bConfigurarCuervo->setText(QString());
        bConfigurarPlaga->setText(QString());
        bConfigurarABB->setText(QString());
        bConfigurarHeap->setText(QString());
        bConfigurarAVL->setText(QString());
        bConfigurarBonus->setText(QString());
        bConfigurarMercado->setText(QString());
        bConfigurarEspanta->setText(QString());
        label->setText(QApplication::translate("InterfazConfiguracion", "Segundos en el que se mueve una casilla", nullptr));
        delayMovimientoGranjero->setSuffix(QApplication::translate("InterfazConfiguracion", " seg", nullptr));
        label_2->setText(QApplication::translate("InterfazConfiguracion", "% de aparici\303\263n", nullptr));
        label_3->setText(QApplication::translate("InterfazConfiguracion", "cant / seg", nullptr));
        cantidadTardanAparecerOvejas->setSuffix(QApplication::translate("InterfazConfiguracion", " seg", nullptr));
        label_4->setText(QApplication::translate("InterfazConfiguracion", "frutos / seg", nullptr));
        segundosOvejaComeFrutos->setSuffix(QApplication::translate("InterfazConfiguracion", " seg", nullptr));
        label_5->setText(QApplication::translate("InterfazConfiguracion", "ABB", nullptr));
        label_6->setText(QApplication::translate("InterfazConfiguracion", "Heap", nullptr));
        label_7->setText(QApplication::translate("InterfazConfiguracion", "AVL", nullptr));
        label_8->setText(QApplication::translate("InterfazConfiguracion", "Bonus", nullptr));
        label_9->setText(QApplication::translate("InterfazConfiguracion", "cant / seg", nullptr));
        cantidadTardanAparecerCuervos->setSuffix(QApplication::translate("InterfazConfiguracion", " seg", nullptr));
        segundosCuervoComeFrutos->setSuffix(QApplication::translate("InterfazConfiguracion", " seg", nullptr));
        label_10->setText(QApplication::translate("InterfazConfiguracion", "% de aparici\303\263n", nullptr));
        label_12->setText(QApplication::translate("InterfazConfiguracion", "frutos / seg", nullptr));
        label_11->setText(QApplication::translate("InterfazConfiguracion", "Cada \"x\" seg", nullptr));
        cantidadTardaAparecerPlaga->setSuffix(QApplication::translate("InterfazConfiguracion", " seg", nullptr));
        label_13->setText(QApplication::translate("InterfazConfiguracion", "% de aparici\303\263n", nullptr));
        label_14->setText(QApplication::translate("InterfazConfiguracion", "Destruye arbol en \"x\" seg", nullptr));
        cantidadSegundosDestruyePlaga->setSuffix(QApplication::translate("InterfazConfiguracion", " seg", nullptr));
        label_15->setText(QApplication::translate("InterfazConfiguracion", "Abre", nullptr));
        label_16->setText(QApplication::translate("InterfazConfiguracion", "Cierra", nullptr));
        tiempoAbreMercado->setSuffix(QApplication::translate("InterfazConfiguracion", " seg", nullptr));
        tiempoCierraMercado->setSuffix(QApplication::translate("InterfazConfiguracion", " seg", nullptr));
        costoEspanta->setPrefix(QApplication::translate("InterfazConfiguracion", "$", nullptr));
        costoEspanta->setSuffix(QString());
        label_17->setText(QApplication::translate("InterfazConfiguracion", "Cant M\303\241xima", nullptr));
        costoABB->setPrefix(QApplication::translate("InterfazConfiguracion", "$", nullptr));
        costoABB->setSuffix(QString());
        crecimientoABB->setSuffix(QApplication::translate("InterfazConfiguracion", " seg", nullptr));
        label_20->setText(QApplication::translate("InterfazConfiguracion", "Crecimiento (seg)", nullptr));
        label_21->setText(QApplication::translate("InterfazConfiguracion", "fruto / seg", nullptr));
        cantSegCosechaABB->setSuffix(QApplication::translate("InterfazConfiguracion", " seg", nullptr));
        mayorVentaFrutosABB->setPrefix(QApplication::translate("InterfazConfiguracion", "$", nullptr));
        mayorVentaFrutosABB->setSuffix(QString());
        label_22->setText(QApplication::translate("InterfazConfiguracion", "Venta         menor / mayor", nullptr));
        menorVentaFrutosABB->setPrefix(QApplication::translate("InterfazConfiguracion", "$", nullptr));
        menorVentaFrutosABB->setSuffix(QString());
        label_23->setText(QApplication::translate("InterfazConfiguracion", "Crecimiento (seg)", nullptr));
        costoHeap->setPrefix(QApplication::translate("InterfazConfiguracion", "$", nullptr));
        costoHeap->setSuffix(QString());
        cantSegCosechaHeap->setSuffix(QApplication::translate("InterfazConfiguracion", " seg", nullptr));
        label_25->setText(QApplication::translate("InterfazConfiguracion", "fruto / seg", nullptr));
        label_26->setText(QApplication::translate("InterfazConfiguracion", "Venta         menor / mayor", nullptr));
        menorVentaFrutosHeap->setPrefix(QApplication::translate("InterfazConfiguracion", "$", nullptr));
        menorVentaFrutosHeap->setSuffix(QString());
        mayorVentaFrutosHeap->setPrefix(QApplication::translate("InterfazConfiguracion", "$", nullptr));
        mayorVentaFrutosHeap->setSuffix(QString());
        crecimientoHeap->setSuffix(QApplication::translate("InterfazConfiguracion", " seg", nullptr));
        label_27->setText(QApplication::translate("InterfazConfiguracion", "Crecimiento (seg)", nullptr));
        costoAVL->setPrefix(QApplication::translate("InterfazConfiguracion", "$", nullptr));
        costoAVL->setSuffix(QString());
        cantSegCosechaAVL->setSuffix(QApplication::translate("InterfazConfiguracion", " seg", nullptr));
        label_29->setText(QApplication::translate("InterfazConfiguracion", "fruto / seg", nullptr));
        label_30->setText(QApplication::translate("InterfazConfiguracion", "Venta         menor / mayor", nullptr));
        menorVentaFrutosAVL->setPrefix(QApplication::translate("InterfazConfiguracion", "$", nullptr));
        menorVentaFrutosAVL->setSuffix(QString());
        mayorVentaFrutosAVL->setPrefix(QApplication::translate("InterfazConfiguracion", "$", nullptr));
        mayorVentaFrutosAVL->setSuffix(QString());
        crecimientoAVL->setSuffix(QApplication::translate("InterfazConfiguracion", " seg", nullptr));
        label_31->setText(QApplication::translate("InterfazConfiguracion", "Crecimiento (seg)", nullptr));
        costoBonus->setPrefix(QApplication::translate("InterfazConfiguracion", "$", nullptr));
        costoBonus->setSuffix(QString());
        cantSegCosechaBonus->setSuffix(QApplication::translate("InterfazConfiguracion", " seg", nullptr));
        label_33->setText(QApplication::translate("InterfazConfiguracion", "fruto / seg", nullptr));
        label_34->setText(QApplication::translate("InterfazConfiguracion", "Venta         menor / mayor", nullptr));
        menorVentaFrutosBonus->setPrefix(QApplication::translate("InterfazConfiguracion", "$", nullptr));
        menorVentaFrutosBonus->setSuffix(QString());
        mayorVentaFrutosBonus->setPrefix(QApplication::translate("InterfazConfiguracion", "$", nullptr));
        mayorVentaFrutosBonus->setSuffix(QString());
        crecimientoBonus->setSuffix(QApplication::translate("InterfazConfiguracion", " seg", nullptr));
        label_35->setText(QApplication::translate("InterfazConfiguracion", "Tarea Programada #2 Estructuras de Datos               Prof: Diego Mora                    Estudiantes: Esteban Chavarr\303\255a y Pa\303\272l Esteban", nullptr));
    } // retranslateUi

};

namespace Ui {
    class InterfazConfiguracion: public Ui_InterfazConfiguracion {};
} // namespace Ui

QT_END_NAMESPACE

#endif // UI_INTERFAZCONFIGURACION_H
